#!/usr/bin/env zsh

if type tmux &> /dev/null; then
    #if not inside a tmux session, and if no session is started, start a new session
    if [[ -z "$TMUX" && -z $TERMINAL_CONTEXT && "$ENABLE_TMUX" -eq 1 ]]; then
        (tmux -2 attach || tmux -2 new-session)
    fi
fi
