#!/usr/bin/env bash
# atlassian-cli completions
# Generated from `atlassian-cli --help`; regenerate after upgrading the CLI.

_atlassian_cli_data() {
    declare -gA _ATLASSIAN_CLI_SUBS _ATLASSIAN_CLI_OPTS _ATLASSIAN_CLI_ENUM \
        _ATLASSIAN_CLI_ALIAS _ATLASSIAN_CLI_OWN_OPTS

    _ATLASSIAN_CLI_GLOBAL_OPTS="-p= --profile= --config= -f= --format= --envelope -h --help"
    _ATLASSIAN_CLI_FILE_OPTS="--body --config --data --dir --file --output --path -d -o"
    _ATLASSIAN_CLI_ENUM["--archived"]="true false"
    _ATLASSIAN_CLI_ENUM["--enabled"]="true false"
    _ATLASSIAN_CLI_ENUM["--format"]="table json yaml csv quiet markdown"
    _ATLASSIAN_CLI_ENUM["--kind"]="footer inline"
    _ATLASSIAN_CLI_ENUM["--method"]="get post put patch delete head"
    _ATLASSIAN_CLI_ENUM["--released"]="true false"
    _ATLASSIAN_CLI_ENUM["--side"]="new old"
    _ATLASSIAN_CLI_ENUM["--status"]="current draft"
    _ATLASSIAN_CLI_ENUM["-X"]="get post put patch delete head"
    _ATLASSIAN_CLI_ENUM["-f"]="table json yaml csv quiet markdown"
    _ATLASSIAN_CLI_ALIAS["bb"]="bitbucket"

    _ATLASSIAN_CLI_SUBS["."]="jira confluence bitbucket bb jsm opsgenie bamboo auth"
    _ATLASSIAN_CLI_OPTS["."]="-p= --profile= --config= -f= --format= --envelope --debug -h --help -V --version"
    _ATLASSIAN_CLI_OWN_OPTS["."]=1
    _ATLASSIAN_CLI_SUBS["auth"]="login logout list status whoami test"
    _ATLASSIAN_CLI_OPTS["auth list"]="--all"
    _ATLASSIAN_CLI_OPTS["auth login"]="--profile= --base-url= --config= --email= -f= --format= --envelope --token= --default --bitbucket --bearer --workspace= -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["auth login"]=1
    _ATLASSIAN_CLI_OPTS["auth logout"]="--profile= --config= --remove-profile --bitbucket -f= --format= --envelope -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["auth logout"]=1
    _ATLASSIAN_CLI_OPTS["auth status"]="--profile= --config= --configured-only -f= --format= --envelope -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["auth status"]=1
    _ATLASSIAN_CLI_OPTS["auth test"]="--profile= --bitbucket --config= -f= --format= --envelope -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["auth test"]=1
    _ATLASSIAN_CLI_OPTS["auth whoami"]="--profile= --config= -f= --format= --envelope -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["auth whoami"]=1
    _ATLASSIAN_CLI_SUBS["bamboo"]="project plan branch build deploy agent artifact info queue"
    _ATLASSIAN_CLI_SUBS["bamboo agent"]="list get enable disable capabilities"
    _ATLASSIAN_CLI_SUBS["bamboo artifact"]="list download"
    _ATLASSIAN_CLI_OPTS["bamboo artifact download"]="--name= -o= --output="
    _ATLASSIAN_CLI_SUBS["bamboo branch"]="list get create delete enable disable"
    _ATLASSIAN_CLI_OPTS["bamboo branch create"]="--name= --vcs-branch="
    _ATLASSIAN_CLI_OPTS["bamboo branch list"]="--limit="
    _ATLASSIAN_CLI_SUBS["bamboo build"]="list get latest run stop logs comment add-label remove-label"
    _ATLASSIAN_CLI_OPTS["bamboo build add-label"]="--label="
    _ATLASSIAN_CLI_OPTS["bamboo build comment"]="--message="
    _ATLASSIAN_CLI_OPTS["bamboo build list"]="--limit="
    _ATLASSIAN_CLI_OPTS["bamboo build logs"]="--job="
    _ATLASSIAN_CLI_OPTS["bamboo build remove-label"]="--label="
    _ATLASSIAN_CLI_OPTS["bamboo build run"]="--stage= --revision="
    _ATLASSIAN_CLI_SUBS["bamboo deploy"]="projects project environments environment results trigger versions"
    _ATLASSIAN_CLI_OPTS["bamboo deploy projects"]="--limit="
    _ATLASSIAN_CLI_OPTS["bamboo deploy results"]="--limit="
    _ATLASSIAN_CLI_OPTS["bamboo deploy trigger"]="--version-id="
    _ATLASSIAN_CLI_OPTS["bamboo deploy versions"]="--limit="
    _ATLASSIAN_CLI_SUBS["bamboo plan"]="list get enable disable favorite unfavorite"
    _ATLASSIAN_CLI_OPTS["bamboo plan list"]="--limit="
    _ATLASSIAN_CLI_SUBS["bamboo project"]="list get"
    _ATLASSIAN_CLI_OPTS["bamboo project list"]="--limit="
    _ATLASSIAN_CLI_SUBS["bitbucket"]="repo branch pr workspace project pipeline webhook ssh-key permission commit bulk whoami"
    _ATLASSIAN_CLI_OPTS["bitbucket"]="--workspace= --repo="
    _ATLASSIAN_CLI_SUBS["bitbucket branch"]="list get create delete protect unprotect restrictions"
    _ATLASSIAN_CLI_OPTS["bitbucket branch"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket branch create"]="--from= --workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket branch delete"]="--force --workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket branch get"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket branch list"]="--limit= --workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket branch protect"]="--pattern= --workspace= --kind= --approvals="
    _ATLASSIAN_CLI_OPTS["bitbucket branch restrictions"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket branch unprotect"]="--workspace="
    _ATLASSIAN_CLI_SUBS["bitbucket bulk"]="archive-repos delete-branches"
    _ATLASSIAN_CLI_OPTS["bitbucket bulk"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket bulk archive-repos"]="--days= --workspace= --dry-run --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket bulk delete-branches"]="--exclude= --workspace= --dry-run"
    _ATLASSIAN_CLI_SUBS["bitbucket commit"]="list get diff browse"
    _ATLASSIAN_CLI_OPTS["bitbucket commit"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket commit browse"]="--commit= --workspace= --path="
    _ATLASSIAN_CLI_OPTS["bitbucket commit diff"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket commit get"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket commit list"]="--branch= --workspace= --limit="
    _ATLASSIAN_CLI_SUBS["bitbucket permission"]="list grant revoke"
    _ATLASSIAN_CLI_OPTS["bitbucket permission"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket permission grant"]="--user-uuid= --workspace= --permission="
    _ATLASSIAN_CLI_OPTS["bitbucket permission list"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket permission revoke"]="--workspace="
    _ATLASSIAN_CLI_SUBS["bitbucket pipeline"]="list get latest trigger stop logs watch steps status rerun var env"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline"]="--workspace= --repo="
    _ATLASSIAN_CLI_SUBS["bitbucket pipeline env"]="list"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline env"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline env list"]="--limit= --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline get"]="--pipeline= --workspace= --repo= --steps"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline latest"]="--branch= --workspace= --repo= --steps"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline list"]="--limit= --workspace= --repo= --sort= --recent= --branch= --since= --before= --pr= --all --steps"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline logs"]="--pipeline= --workspace= --repo= --step-uuid= --step= --grep= -i --ignore-case --failed-only"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline rerun"]="--pr= --workspace= --failed-only --repo= --var= --secured"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline status"]="--steps --workspace= --repo= --wait --interval="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline steps"]="--pipeline= --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline stop"]="--pipeline= --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline trigger"]="--ref-name= --workspace= --ref-type= --repo= --var= --secured --custom-pipeline="
    _ATLASSIAN_CLI_SUBS["bitbucket pipeline var"]="list get create update delete"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline var"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline var create"]="--key= --workspace= --repo= --value= --secured --workspace-level --deployment="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline var delete"]="--key= --workspace= --repo= --workspace-level --deployment= --force"
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline var get"]="--key= --workspace= --repo= --workspace-level --deployment="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline var list"]="--workspace= --workspace-level --deployment= --repo= --limit="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline var update"]="--key= --workspace= --repo= --value= --secured --unsecured --workspace-level --deployment="
    _ATLASSIAN_CLI_OPTS["bitbucket pipeline watch"]="--pipeline= --workspace= --interval= --repo= --steps --on-complete= --timeout= --log"
    _ATLASSIAN_CLI_SUBS["bitbucket pr"]="list get create update merge decline approve unapprove diff comments comment resolve-comment reopen-comment reviewers"
    _ATLASSIAN_CLI_OPTS["bitbucket pr"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket pr approve"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr comment"]="--text= --workspace= --parent= --path= --line= --side="
    _ATLASSIAN_CLI_OPTS["bitbucket pr comments"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr create"]="--title= --workspace= --source= --destination= --description= --reviewers="
    _ATLASSIAN_CLI_OPTS["bitbucket pr decline"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr diff"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr get"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr list"]="--state= --workspace= --limit="
    _ATLASSIAN_CLI_OPTS["bitbucket pr merge"]="--strategy= --workspace= --message="
    _ATLASSIAN_CLI_OPTS["bitbucket pr reopen-comment"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr resolve-comment"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr reviewers"]="--add= --workspace= --all"
    _ATLASSIAN_CLI_OPTS["bitbucket pr unapprove"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket pr update"]="--title= --workspace= --description="
    _ATLASSIAN_CLI_SUBS["bitbucket project"]="list get create update delete"
    _ATLASSIAN_CLI_OPTS["bitbucket project"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket project create"]="--name= --workspace= --description= --repo= --private"
    _ATLASSIAN_CLI_OPTS["bitbucket project delete"]="--force --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket project get"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket project list"]="--limit= --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket project update"]="--name= --workspace= --description= --repo="
    _ATLASSIAN_CLI_SUBS["bitbucket repo"]="list get create update delete"
    _ATLASSIAN_CLI_OPTS["bitbucket repo"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket repo create"]="--name= --workspace= --description= --repo= --private --project="
    _ATLASSIAN_CLI_OPTS["bitbucket repo delete"]="--force --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket repo get"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket repo list"]="--limit= --workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket repo update"]="--name= --workspace= --description= --repo= --language="
    _ATLASSIAN_CLI_SUBS["bitbucket ssh-key"]="list add delete"
    _ATLASSIAN_CLI_OPTS["bitbucket ssh-key"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket ssh-key add"]="--label= --workspace= --key="
    _ATLASSIAN_CLI_OPTS["bitbucket ssh-key delete"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket ssh-key list"]="--workspace="
    _ATLASSIAN_CLI_SUBS["bitbucket webhook"]="list create delete"
    _ATLASSIAN_CLI_OPTS["bitbucket webhook"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket webhook create"]="--url= --workspace= --description= --events= --active"
    _ATLASSIAN_CLI_OPTS["bitbucket webhook delete"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket webhook list"]="--workspace="
    _ATLASSIAN_CLI_OPTS["bitbucket whoami"]="--workspace= --repo="
    _ATLASSIAN_CLI_SUBS["bitbucket workspace"]="list get"
    _ATLASSIAN_CLI_OPTS["bitbucket workspace"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket workspace get"]="--workspace= --repo="
    _ATLASSIAN_CLI_OPTS["bitbucket workspace list"]="--limit= --workspace= --repo="
    _ATLASSIAN_CLI_SUBS["confluence"]="space page folder blog attachment search bulk analytics"
    _ATLASSIAN_CLI_SUBS["confluence analytics"]="page-views space-stats"
    _ATLASSIAN_CLI_OPTS["confluence analytics page-views"]="--from="
    _ATLASSIAN_CLI_SUBS["confluence attachment"]="list get upload download delete"
    _ATLASSIAN_CLI_OPTS["confluence attachment delete"]="--force"
    _ATLASSIAN_CLI_OPTS["confluence attachment download"]="--output="
    _ATLASSIAN_CLI_OPTS["confluence attachment upload"]="--file= --comment="
    _ATLASSIAN_CLI_SUBS["confluence blog"]="list get create update publish delete"
    _ATLASSIAN_CLI_OPTS["confluence blog create"]="--space= --title= --body="
    _ATLASSIAN_CLI_OPTS["confluence blog delete"]="--force"
    _ATLASSIAN_CLI_OPTS["confluence blog get"]="--body-only"
    _ATLASSIAN_CLI_OPTS["confluence blog list"]="--space= --limit="
    _ATLASSIAN_CLI_OPTS["confluence blog publish"]="--body= --title= --message="
    _ATLASSIAN_CLI_OPTS["confluence blog update"]="--title= --body= --status= --message="
    _ATLASSIAN_CLI_SUBS["confluence bulk"]="delete add-labels export"
    _ATLASSIAN_CLI_OPTS["confluence bulk add-labels"]="--cql= --labels= --dry-run --concurrency="
    _ATLASSIAN_CLI_OPTS["confluence bulk delete"]="--cql= --dry-run --concurrency="
    _ATLASSIAN_CLI_OPTS["confluence bulk export"]="--cql= -p= --profile= --config= --output= --format= --envelope -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["confluence bulk export"]=1
    _ATLASSIAN_CLI_SUBS["confluence folder"]="get create delete"
    _ATLASSIAN_CLI_OPTS["confluence folder create"]="--space= --title= --parent="
    _ATLASSIAN_CLI_OPTS["confluence folder delete"]="--force"
    _ATLASSIAN_CLI_SUBS["confluence page"]="list get create update publish delete versions add-label remove-label comments add-comment get-restrictions add-restriction remove-restriction"
    _ATLASSIAN_CLI_OPTS["confluence page add-comment"]="--parent= --kind="
    _ATLASSIAN_CLI_OPTS["confluence page add-restriction"]="--operation= --subject-type= --subject-id="
    _ATLASSIAN_CLI_OPTS["confluence page comments"]="--full --replies"
    _ATLASSIAN_CLI_OPTS["confluence page create"]="--space= --title= --body= --parent="
    _ATLASSIAN_CLI_OPTS["confluence page delete"]="--force"
    _ATLASSIAN_CLI_OPTS["confluence page get"]="--body-only"
    _ATLASSIAN_CLI_OPTS["confluence page list"]="--space= --limit="
    _ATLASSIAN_CLI_OPTS["confluence page publish"]="--body= --title= --message="
    _ATLASSIAN_CLI_OPTS["confluence page remove-restriction"]="--operation= --subject-type= --subject-id="
    _ATLASSIAN_CLI_OPTS["confluence page update"]="--title= --body= --status= --message="
    _ATLASSIAN_CLI_SUBS["confluence search"]="cql text in-space params"
    _ATLASSIAN_CLI_OPTS["confluence search cql"]="--limit="
    _ATLASSIAN_CLI_OPTS["confluence search in-space"]="--limit="
    _ATLASSIAN_CLI_OPTS["confluence search params"]="--space= --type= --creator= --label= --title= --text= --show-query --limit="
    _ATLASSIAN_CLI_OPTS["confluence search text"]="--limit="
    _ATLASSIAN_CLI_SUBS["confluence space"]="list get create update delete permissions add-permission"
    _ATLASSIAN_CLI_OPTS["confluence space add-permission"]="--permission= --subject-type= --subject-id="
    _ATLASSIAN_CLI_OPTS["confluence space create"]="--key= --name= --description="
    _ATLASSIAN_CLI_OPTS["confluence space delete"]="--force"
    _ATLASSIAN_CLI_OPTS["confluence space list"]="--limit= --space-type="
    _ATLASSIAN_CLI_OPTS["confluence space update"]="--name= --description="
    _ATLASSIAN_CLI_SUBS["jira"]="issue attachment project components versions roles fields workflows bulk automation webhooks audit api"
    _ATLASSIAN_CLI_OPTS["jira api"]="-X= --method= -d= --data= -H= --header= --query= -i --include --output= --dry-run --force --timeout="
    _ATLASSIAN_CLI_SUBS["jira attachment"]="list get download upload delete"
    _ATLASSIAN_CLI_OPTS["jira attachment delete"]="--force"
    _ATLASSIAN_CLI_OPTS["jira attachment download"]="--issue= -o= --output= --dir= --force"
    _ATLASSIAN_CLI_OPTS["jira attachment upload"]="--file="
    _ATLASSIAN_CLI_SUBS["jira audit"]="list export"
    _ATLASSIAN_CLI_OPTS["jira audit export"]="--from= -p= --profile= --config= --to= --filter= --envelope --output= --format= -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["jira audit export"]=1
    _ATLASSIAN_CLI_OPTS["jira audit list"]="--from= --to= --filter= --limit="
    _ATLASSIAN_CLI_SUBS["jira automation"]="list get create update enable disable delete export"
    _ATLASSIAN_CLI_OPTS["jira automation create"]="--name= --description= --definition="
    _ATLASSIAN_CLI_OPTS["jira automation delete"]="--force"
    _ATLASSIAN_CLI_OPTS["jira automation export"]="--output="
    _ATLASSIAN_CLI_OPTS["jira automation update"]="--name= --description="
    _ATLASSIAN_CLI_SUBS["jira bulk"]="transition assign label export import"
    _ATLASSIAN_CLI_OPTS["jira bulk assign"]="--jql= --assignee= --dry-run --concurrency="
    _ATLASSIAN_CLI_OPTS["jira bulk export"]="--jql= -p= --profile= --config= --output= --format= --envelope --fields= -h --help"
    _ATLASSIAN_CLI_OWN_OPTS["jira bulk export"]=1
    _ATLASSIAN_CLI_OPTS["jira bulk import"]="--file= --project= --dry-run --concurrency="
    _ATLASSIAN_CLI_OPTS["jira bulk label"]="--jql= --action= --labels= --dry-run --concurrency="
    _ATLASSIAN_CLI_OPTS["jira bulk transition"]="--jql= --transition= --dry-run --concurrency="
    _ATLASSIAN_CLI_SUBS["jira components"]="list get create update delete"
    _ATLASSIAN_CLI_OPTS["jira components create"]="--project= --name= --description= --lead="
    _ATLASSIAN_CLI_OPTS["jira components update"]="--name= --description="
    _ATLASSIAN_CLI_SUBS["jira fields"]="list get create delete"
    _ATLASSIAN_CLI_OPTS["jira fields create"]="--name= --description= --field-type="
    _ATLASSIAN_CLI_SUBS["jira issue"]="search get transitions create update delete transition assign unassign watchers links comments"
    _ATLASSIAN_CLI_OPTS["jira issue assign"]="--assignee="
    _ATLASSIAN_CLI_SUBS["jira issue comments"]="list add update delete"
    _ATLASSIAN_CLI_OPTS["jira issue comments add"]="--body="
    _ATLASSIAN_CLI_OPTS["jira issue comments list"]="--full"
    _ATLASSIAN_CLI_OPTS["jira issue comments update"]="--body="
    _ATLASSIAN_CLI_OPTS["jira issue create"]="--project= --issue-type= --summary= --description= --assignee= --priority= --field= --sprint="
    _ATLASSIAN_CLI_OPTS["jira issue delete"]="--force"
    _ATLASSIAN_CLI_SUBS["jira issue links"]="list create delete"
    _ATLASSIAN_CLI_OPTS["jira issue links create"]="--link-type="
    _ATLASSIAN_CLI_OPTS["jira issue search"]="--jql= --assignee= --status= --priority= --label= --type= --project= --text= --show-query --limit="
    _ATLASSIAN_CLI_OPTS["jira issue transition"]="--transition="
    _ATLASSIAN_CLI_OPTS["jira issue update"]="--summary= --description= --priority= --field= --sprint="
    _ATLASSIAN_CLI_SUBS["jira issue watchers"]="list add remove"
    _ATLASSIAN_CLI_SUBS["jira project"]="list get create update delete"
    _ATLASSIAN_CLI_OPTS["jira project create"]="--key= --name= --project-type= --lead= --description="
    _ATLASSIAN_CLI_OPTS["jira project delete"]="--force"
    _ATLASSIAN_CLI_OPTS["jira project update"]="--name= --description= --lead="
    _ATLASSIAN_CLI_SUBS["jira roles"]="list get actors add-actor remove-actor"
    _ATLASSIAN_CLI_OPTS["jira roles add-actor"]="--user="
    _ATLASSIAN_CLI_OPTS["jira roles remove-actor"]="--user="
    _ATLASSIAN_CLI_SUBS["jira versions"]="list get create update delete merge"
    _ATLASSIAN_CLI_OPTS["jira versions create"]="--project= --name= --description= --start-date= --release-date= --released --archived"
    _ATLASSIAN_CLI_OPTS["jira versions update"]="--name= --description= --released= --archived="
    _ATLASSIAN_CLI_SUBS["jira webhooks"]="list get create update enable disable delete test"
    _ATLASSIAN_CLI_OPTS["jira webhooks create"]="--name= --url= --events= --enabled --jql-filter="
    _ATLASSIAN_CLI_OPTS["jira webhooks delete"]="--force"
    _ATLASSIAN_CLI_OPTS["jira webhooks update"]="--name= --url= --events= --enabled="
    _ATLASSIAN_CLI_SUBS["jira workflows"]="list get export"
    _ATLASSIAN_CLI_OPTS["jira workflows export"]="--output="
    _ATLASSIAN_CLI_SUBS["jsm"]="service-desk request queue approval sla customer organization request-type kb feedback"
    _ATLASSIAN_CLI_SUBS["jsm approval"]="list get approve decline"
    _ATLASSIAN_CLI_OPTS["jsm approval approve"]="--approval-id="
    _ATLASSIAN_CLI_OPTS["jsm approval decline"]="--approval-id="
    _ATLASSIAN_CLI_OPTS["jsm approval get"]="--approval-id="
    _ATLASSIAN_CLI_SUBS["jsm customer"]="create revoke-portal-access"
    _ATLASSIAN_CLI_OPTS["jsm customer create"]="--email= --display-name="
    _ATLASSIAN_CLI_OPTS["jsm customer revoke-portal-access"]="--account-id="
    _ATLASSIAN_CLI_SUBS["jsm feedback"]="get submit delete"
    _ATLASSIAN_CLI_OPTS["jsm feedback submit"]="--rating= --comment="
    _ATLASSIAN_CLI_SUBS["jsm kb"]="search"
    _ATLASSIAN_CLI_OPTS["jsm kb search"]="--query= --servicedesk-id= --limit="
    _ATLASSIAN_CLI_SUBS["jsm organization"]="list get create delete users add-user remove-user"
    _ATLASSIAN_CLI_OPTS["jsm organization add-user"]="--account-id="
    _ATLASSIAN_CLI_OPTS["jsm organization create"]="--name="
    _ATLASSIAN_CLI_OPTS["jsm organization list"]="--limit="
    _ATLASSIAN_CLI_OPTS["jsm organization remove-user"]="--account-id="
    _ATLASSIAN_CLI_OPTS["jsm organization users"]="--limit="
    _ATLASSIAN_CLI_SUBS["jsm queue"]="list get issues"
    _ATLASSIAN_CLI_OPTS["jsm queue issues"]="--limit="
    _ATLASSIAN_CLI_SUBS["jsm request"]="list get create transitions transition status comments add-comment participants add-participant remove-participant subscribe unsubscribe"
    _ATLASSIAN_CLI_OPTS["jsm request add-comment"]="--body= --public"
    _ATLASSIAN_CLI_OPTS["jsm request add-participant"]="--account-id="
    _ATLASSIAN_CLI_OPTS["jsm request comments"]="--limit="
    _ATLASSIAN_CLI_OPTS["jsm request create"]="--servicedesk-id= --request-type-id= --summary= --description="
    _ATLASSIAN_CLI_OPTS["jsm request list"]="--servicedesk-id= --limit="
    _ATLASSIAN_CLI_OPTS["jsm request remove-participant"]="--account-id="
    _ATLASSIAN_CLI_OPTS["jsm request transition"]="--transition="
    _ATLASSIAN_CLI_SUBS["jsm request-type"]="list get fields groups"
    _ATLASSIAN_CLI_OPTS["jsm request-type list"]="--servicedesk-id= --limit="
    _ATLASSIAN_CLI_SUBS["jsm service-desk"]="list get customers add-customer remove-customer organizations add-organization remove-organization"
    _ATLASSIAN_CLI_OPTS["jsm service-desk add-customer"]="--account-id="
    _ATLASSIAN_CLI_OPTS["jsm service-desk add-organization"]="--org-id="
    _ATLASSIAN_CLI_OPTS["jsm service-desk customers"]="--limit="
    _ATLASSIAN_CLI_OPTS["jsm service-desk list"]="--limit="
    _ATLASSIAN_CLI_OPTS["jsm service-desk organizations"]="--limit="
    _ATLASSIAN_CLI_OPTS["jsm service-desk remove-customer"]="--account-id="
    _ATLASSIAN_CLI_OPTS["jsm service-desk remove-organization"]="--org-id="
    _ATLASSIAN_CLI_SUBS["jsm sla"]="list get"
    _ATLASSIAN_CLI_OPTS["jsm sla get"]="--sla-id="
    _ATLASSIAN_CLI_SUBS["opsgenie"]="alert incident schedule team escalation service heartbeat"
    _ATLASSIAN_CLI_SUBS["opsgenie alert"]="list get create close ack unack snooze escalate assign add-note delete recipients logs notes"
    _ATLASSIAN_CLI_OPTS["opsgenie alert ack"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie alert add-note"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie alert assign"]="--owner-id= --note="
    _ATLASSIAN_CLI_OPTS["opsgenie alert close"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie alert create"]="--message= --alias= --description= --priority= --source= --tags="
    _ATLASSIAN_CLI_OPTS["opsgenie alert escalate"]="--escalation-id= --note="
    _ATLASSIAN_CLI_OPTS["opsgenie alert list"]="--query= --limit= --status="
    _ATLASSIAN_CLI_OPTS["opsgenie alert logs"]="--limit="
    _ATLASSIAN_CLI_OPTS["opsgenie alert notes"]="--limit="
    _ATLASSIAN_CLI_OPTS["opsgenie alert snooze"]="--end-time= --note="
    _ATLASSIAN_CLI_OPTS["opsgenie alert unack"]="--note="
    _ATLASSIAN_CLI_SUBS["opsgenie escalation"]="list get create delete"
    _ATLASSIAN_CLI_OPTS["opsgenie escalation create"]="--name= --description= --team-id="
    _ATLASSIAN_CLI_OPTS["opsgenie escalation list"]="--limit="
    _ATLASSIAN_CLI_SUBS["opsgenie heartbeat"]="list get create delete enable disable ping"
    _ATLASSIAN_CLI_OPTS["opsgenie heartbeat create"]="--name= --description= --interval= --interval-unit= --team-id="
    _ATLASSIAN_CLI_SUBS["opsgenie incident"]="list get create close resolve reopen add-responder add-note delete timeline"
    _ATLASSIAN_CLI_OPTS["opsgenie incident add-note"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie incident add-responder"]="--responder-id= --responder-type= --note="
    _ATLASSIAN_CLI_OPTS["opsgenie incident close"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie incident create"]="--message= --description= --priority= --tags= --service-ids="
    _ATLASSIAN_CLI_OPTS["opsgenie incident list"]="--query= --limit="
    _ATLASSIAN_CLI_OPTS["opsgenie incident reopen"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie incident resolve"]="--note="
    _ATLASSIAN_CLI_OPTS["opsgenie incident timeline"]="--limit="
    _ATLASSIAN_CLI_SUBS["opsgenie schedule"]="list get create delete enable disable on-call timeline export"
    _ATLASSIAN_CLI_OPTS["opsgenie schedule create"]="--name= --description= --timezone= --team-id="
    _ATLASSIAN_CLI_OPTS["opsgenie schedule list"]="--limit="
    _ATLASSIAN_CLI_OPTS["opsgenie schedule on-call"]="--date="
    _ATLASSIAN_CLI_OPTS["opsgenie schedule timeline"]="--interval= --interval-unit= --date="
    _ATLASSIAN_CLI_SUBS["opsgenie service"]="list get create delete"
    _ATLASSIAN_CLI_OPTS["opsgenie service create"]="--name= --team-id= --description="
    _ATLASSIAN_CLI_OPTS["opsgenie service list"]="--limit="
    _ATLASSIAN_CLI_SUBS["opsgenie team"]="list get create delete members add-member remove-member on-call"
    _ATLASSIAN_CLI_OPTS["opsgenie team add-member"]="--user-id= --role="
    _ATLASSIAN_CLI_OPTS["opsgenie team create"]="--name= --description="
    _ATLASSIAN_CLI_OPTS["opsgenie team list"]="--limit="
    _ATLASSIAN_CLI_OPTS["opsgenie team on-call"]="--date="
    _ATLASSIAN_CLI_OPTS["opsgenie team remove-member"]="--user-id="

    _ATLASSIAN_CLI_LOADED=1
}

_atlassian_cli() {
    [[ -n ${_ATLASSIAN_CLI_LOADED-} ]] || _atlassian_cli_data

    local cur prev node=. candidate token opts i
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    for (( i = 1; i < COMP_CWORD; i++ )); do
        token=${COMP_WORDS[i]}
        [[ -z $token || $token == -* ]] && continue
        if [[ $node == . ]]; then candidate=$token; else candidate="$node $token"; fi
        candidate=${_ATLASSIAN_CLI_ALIAS[$candidate]:-$candidate}
        if [[ -v _ATLASSIAN_CLI_SUBS[$candidate] || -v _ATLASSIAN_CLI_OPTS[$candidate] ]]; then
            node=$candidate
        fi
    done

    opts="${_ATLASSIAN_CLI_OPTS[$node]-}"
    [[ -v _ATLASSIAN_CLI_OWN_OPTS[$node] ]] || opts="$opts $_ATLASSIAN_CLI_GLOBAL_OPTS"

    # the word after an option that takes a value completes as that value
    if [[ $prev == -* && " $opts " == *" $prev= "* ]]; then
        if [[ -n ${_ATLASSIAN_CLI_ENUM[$prev]-} ]]; then
            mapfile -t COMPREPLY < <(compgen -W "${_ATLASSIAN_CLI_ENUM[$prev]}" -- "$cur")
        elif [[ " $_ATLASSIAN_CLI_FILE_OPTS " == *" $prev "* ]]; then
            mapfile -t COMPREPLY < <(compgen -f -- "$cur")
        else
            COMPREPLY=()
        fi
        return
    fi

    if [[ $cur == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts//=/}" -- "$cur")
        return
    fi

    mapfile -t COMPREPLY < <(compgen -W "${_ATLASSIAN_CLI_SUBS[$node]-}" -- "$cur")
}

complete -F _atlassian_cli atlassian-cli
