[tools]
age = "latest"
bun = "latest"
direnv = "latest"
java = "corretto-23"
maven = "3"
node = "lts"
rust = "latest"
sops = "latest"
usage = "latest"
"npm:aicommit2" = "latest"
"npm:prettier" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"cargo:cargo-update" = "latest"
"cargo:rust-script" = "latest"
go = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:rulesync" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:opencode-ai" = "latest"

[settings]
experimental = true
