[tools]
"cargo:cargo-update" = "latest"
"cargo:nuls" = "latest"
"cargo:pay-respects" = "latest"
"cargo:rust-script" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mixedbread/mgrep" = "latest"
"npm:@rama_nigg/open-cursor" = "latest"
"npm:aicommit2" = "latest"
"npm:claudekit-cli" = "latest"
"npm:prettier" = "latest"
"npm:rulesync" = "latest"
age = "latest"
bun = "latest"
direnv = "latest"
go = "latest"
java = "corretto-25"
maven = "3"
node = "lts"
opencode = "latest"
rust = "latest"
sops = "latest"
usage = "latest"
uv = "latest"

[settings]
experimental = true
http_timeout = "120"
